simulation:
  max_rounds: 10
  agents_per_round: 4

agent_settings:
  context_history_limit: 20
  private_chat_limit: 10
  
communication:
  forum_enabled: true
  private_messages_enabled: true
  
problems:
  auto_assign: true
  validation_enabled: true