agent_behavior:
  context_history_limit: 10
  early_phase_rounds: 5
  late_phase_rounds: 15
  mid_phase_rounds: 10
  public_activities_limit: 20
  reviews_context_limit: 5
communication:
  message_volume_threshold_multiplier: 2
  private_message_limit: 10
  recent_interactions_hours: 24
llm:
  max_tokens: 1000
  models:
    honeypot: gpt-4o-mini
    saboteur: gpt-4o-mini
    worker: gpt-4o-mini
  temperature: 0.7
logging:
  console_width: 120
scoring:
  approved_solution_points: 10
  bazinga_bonus: 5
  bazinga_penalty: -10
  good_review_points: 2
  honeypot_detection_bonus: 15
  role_detection_bonus: 10
simulation:
  current_round_time_window: 300
  max_rounds: 20
  turn_sleep_duration: 0.5
suspicion:
  default_efficiency_rating: 50
  default_honeypot_detection: 25
  default_honeypot_suspicion: 15
  default_saboteur_suspicion: 20
  honeypot_detection_threshold: 40
  suspicion_threshold: 60
